spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch
      username: seongwou
      password: seongwou1!
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        type: debug
    open-in-view: false
  batch:
    job:
      names: ${job.name:NONE}

logging.level:
  org.springframework.batch: DEBUG
  org.springframework.transaction: DEBUG
  org.springframework.orm.jpa: DEBUG
  org.springframework.jdbc: TRACE
  javax.persistence: TRACE
  org.hibernate: DEBUG
  com.zaxxer.hikari.HikariConfig: DEBUG
  com.zaxxer.hikari: TRACE